#!/usr/bin/env bash
#
# CodeWiki install — configures skill discovery for all supported AI agents.
#
# Usage: ./install.sh
#
# What it does:
#   1. Checks prerequisites (must run from CodeWiki project root)
#   2. Creates .env from .env.example (if not present)
#   3. Creates ~/.code-wiki/config (global config for cross-project usage)
#   4. Symlinks .skills/ into each agent's expected skills directory:
#      Project-local:
#        - .cursor/skills/    → .skills/
#        - .windsurf/skills/  → .skills/
#        - .kiro/skills/      → .skills/
#        - .agents/skills/    → .skills/ (Antigravity, generic)
#      Global:
#        - ~/.gemini/skills/         (Gemini CLI)
#        - ~/.codex/skills/          (Codex)
#        - ~/.hermes/skills/         (Hermes)
#        - ~/.openclaw/skills/       (OpenClaw)
#        - ~/.copilot/skills/        (GitHub Copilot CLI)
#        - ~/.trae/skills/           (Trae)
#        - ~/.trae-cn/skills/        (Trae CN)
#        - ~/.kiro/skills/           (Kiro CLI)
#        - ~/.pi/agent/skills/       (Pi)
#        - ~/.agents/skills/         (OpenCode, Aider, Factory Droid, generic)
#        - ~/.qoder/skills/          (Qoder)
#   5. Prints a summary of what's ready
#
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}✅  $1${NC}"; }
warn()  { echo -e "${YELLOW}⚠️   $1${NC}"; }
error() { echo -e "${RED}❌  $1${NC}"; }

# ── Prerequisites ───────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS_DIR="$SCRIPT_DIR/.skills"

if [ ! -d "$SKILLS_DIR" ]; then
  error "Must run from CodeWiki project root (could not find .skills/ directory)"
  exit 1
fi

if [ ! -f "$SCRIPT_DIR/.env.example" ]; then
  error "Missing .env.example — are you in the CodeWiki project root?"
  exit 1
fi

# ── install_skills <target_dir> <label> [relative|absolute] ─────────────────
# Creates symlinks for each skill in .skills/ into the target directory.
# "relative" emits ../-prefixed targets (for project-local dirs under SCRIPT_DIR).
# "absolute" emits full paths (for global dirs like ~/.gemini/skills/).
install_skills() {
  local target_dir="$1"
  local label="$2"
  local mode="${3:-absolute}"

  mkdir -p "$target_dir"

  for skill in "$SKILLS_DIR"/*/; do
    [ -d "$skill" ] || continue
    local skill_name link_path link_target
    skill_name="$(basename "$skill")"
    link_path="$target_dir/$skill_name"

    if [ "$mode" = "relative" ]; then
      # Compute relative path from target_dir back to .skills/
      local rel="${target_dir#"$SCRIPT_DIR"/}"
      local slashes="${rel//[^\/]/}"
      local depth=$(( ${#slashes} + 1 ))
      local rel_prefix=""
      for (( i=0; i<depth; i++ )); do rel_prefix="../$rel_prefix"; done
      link_target="${rel_prefix}.skills/$skill_name"
    else
      link_target="${skill%/}"
    fi

    # Idempotent: remove existing symlink or placeholder file
    if [ -L "$link_path" ]; then
      rm "$link_path"
    elif [ -d "$link_path" ]; then
      warn "$link_path is a real directory, skipping symlink"
      continue
    elif [ -f "$link_path" ]; then
      rm "$link_path"
    fi

    ln -s "$link_target" "$link_path"

    # Sanity check
    if [ ! -e "$link_path/SKILL.md" ]; then
      warn "Broken link: $link_path → $link_target"
    fi
  done
  info "Installed skills → $label"
}

# ── Banner ──────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║         CodeWiki — Agent Install                  ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Create .env ─────────────────────────────────────────────────────
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  cp "$SCRIPT_DIR/.env.example" "$SCRIPT_DIR/.env"
  info "Created .env from .env.example"
  echo "    → Edit .env to customize CODE_WIKI_OUTPUT_PATH if needed."
else
  info ".env already exists"
fi

# ── Step 2: Global config ~/.code-wiki/config ───────────────────────────────
GLOBAL_CONFIG_DIR="$HOME/.code-wiki"
GLOBAL_CONFIG="$GLOBAL_CONFIG_DIR/config"
mkdir -p "$GLOBAL_CONFIG_DIR"

# Read output path from .env
OUTPUT_PATH=""
if [ -f "$SCRIPT_DIR/.env" ]; then
  OUTPUT_PATH=$(grep -E '^CODE_WIKI_OUTPUT_PATH=' "$SCRIPT_DIR/.env" | cut -d'=' -f2- | sed 's/^"//;s/"$//' || true)
fi

cat > "$GLOBAL_CONFIG" <<EOF
# CodeWiki global config — auto-generated by setup.sh
CODE_WIKI_OUTPUT_PATH="${OUTPUT_PATH:-./wiki}"
CODE_WIKI_REPO="$SCRIPT_DIR"
EOF
info "Global config written to ~/.code-wiki/config"

# ── Step 3: Project-local skill symlinks ────────────────────────────────────
echo ""
echo "── Installing project-local skills ──"

LOCAL_DIRS=(
  ".cursor/skills"
  ".windsurf/skills"
  ".kiro/skills"
  ".agents/skills"
)

for agent_dir in "${LOCAL_DIRS[@]}"; do
  install_skills "$SCRIPT_DIR/$agent_dir" "$agent_dir/" relative
done

# ── Step 4: Global skill symlinks ───────────────────────────────────────────
echo ""
echo "── Installing global skills ──"

install_skills "$HOME/.gemini/skills"       "~/.gemini/skills/ (Gemini CLI)"
install_skills "$HOME/.codex/skills"        "~/.codex/skills/ (Codex)"
install_skills "$HOME/.hermes/skills"       "~/.hermes/skills/ (Hermes)"
install_skills "$HOME/.openclaw/skills"     "~/.openclaw/skills/ (OpenClaw)"
install_skills "$HOME/.copilot/skills"      "~/.copilot/skills/ (GitHub Copilot CLI)"
install_skills "$HOME/.trae/skills"         "~/.trae/skills/ (Trae)"
install_skills "$HOME/.trae-cn/skills"      "~/.trae-cn/skills/ (Trae CN)"
install_skills "$HOME/.kiro/skills"         "~/.kiro/skills/ (Kiro CLI)"
install_skills "$HOME/.pi/agent/skills"     "~/.pi/agent/skills/ (Pi)"
install_skills "$HOME/.agents/skills"       "~/.agents/skills/ (OpenCode, Aider, Droid, generic)"
install_skills "$HOME/.qoder/skills"        "~/.qoder/skills/ (Qoder)"

# ── Step 5: Summary ─────────────────────────────────────────────────────────
SKILL_COUNT=$(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')

echo ""
echo "───────────────────────────────────────────────────"
echo " Setup complete!"
echo ""
echo " Skills found:    $SKILL_COUNT"
echo " Agents ready:    Claude Code, Cursor, Windsurf, Gemini CLI, Codex,"
echo "                  Hermes, OpenClaw, OpenCode, Aider, Factory Droid,"
echo "                  Trae, Trae CN, Kiro, Pi, GitHub Copilot, Kilocode,"
echo "                  Google Antigravity, Qoder"
echo ""
echo " Bootstrap files (already in repo):"
echo "   CLAUDE.md                          → Claude Code / Kilocode"
echo "   GEMINI.md                          → Gemini CLI / Antigravity"
echo "   AGENTS.md                          → Codex, OpenClaw, OpenCode, Aider, Droid, Trae, Hermes, Pi"
echo "   .cursor/rules/code-wiki.mdc        → Cursor (alwaysApply)"
echo "   .windsurf/rules/code-wiki.md       → Windsurf (always-on)"
echo "   .kiro/steering/code-wiki.md        → Kiro (inclusion: always)"
echo "   .github/copilot-instructions.md    → GitHub Copilot (VS Code Chat)"
echo ""
echo " Next steps:"
echo "   1. Go to any code repository you want to document"
echo "   2. Run:  /code-wiki-ingest"
echo "   3. Your wiki will be generated at the configured output path"
echo ""
echo " From any project:"
echo "   /code-wiki-ingest   → analyze code and generate wiki"
echo "   /code-wiki-query    → ask questions against the wiki"
echo "   /code-wiki-lint     → audit wiki health"
echo "   /code-wiki-rebuild  → archive and rebuild"
echo "───────────────────────────────────────────────────"
echo ""
